// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9pjTSv44Ttkbq1ir7_zIz4s948_v91I',
    appId: '1:487414125072:web:468c87936338ef4edb7095',
    messagingSenderId: '487414125072',
    projectId: 'plock-notif',
    authDomain: 'plock-notif.firebaseapp.com',
    storageBucket: 'plock-notif.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEcAunFZvQrTpleVIWCDC4HEugge41Ja0',
    appId: '1:487414125072:android:bfaf2374af3adbe6db7095',
    messagingSenderId: '487414125072',
    projectId: 'plock-notif',
    storageBucket: 'plock-notif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWgVBrQpWkFfa2a4u-oBBhByKoC0qzBI',
    appId: '1:487414125072:ios:454d09584bfb368edb7095',
    messagingSenderId: '487414125072',
    projectId: 'plock-notif',
    storageBucket: 'plock-notif.firebasestorage.app',
    iosBundleId: 'com.example.plockMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKWgVBrQpWkFfa2a4u-oBBhByKoC0qzBI',
    appId: '1:487414125072:ios:4a1c9a1b9c236f6bdb7095',
    messagingSenderId: '487414125072',
    projectId: 'plock-notif',
    storageBucket: 'plock-notif.firebasestorage.app',
    iosBundleId: 'com.plock.plockMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu9pjTSv44Ttkbq1ir7_zIz4s948_v91I',
    appId: '1:487414125072:web:c71e6aac5c81d8cedb7095',
    messagingSenderId: '487414125072',
    projectId: 'plock-notif',
    authDomain: 'plock-notif.firebaseapp.com',
    storageBucket: 'plock-notif.firebasestorage.app',
  );
}
