name: Test For Plock Mobile

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '3.24.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Ensure .env exists
        run: |
          if [ ! -f .env ]; then
            echo ".env file missing, creating from .env.example"
            cp .env.example .env
          fi

      - name: Run Flutter Tests
        run: flutter test --coverage || true

      - name: Fix Slashes in Coverage File
        run: sed -i 's|\\|/|g' coverage/lcov.info || true

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Generate Coverage HTML Report
        run: genhtml coverage/lcov.info -o coverage/html || true

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html
