name: Test For Plock Mobile

on:
  push:
    branches:
      - develop
      - main
      - feat/Plock-177
  pull_request:
    branches:
      - develop
      - main
      - feat/Plock-177

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '3.24.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Ensure .env exists
        run: |
          if [ ! -f .env ]; then
            echo ".env file missing, creating from .env.example"
            cp .env.example .env
          fi

      - name: Run Flutter Tests
        run: flutter test --coverage --timeout=5m --verbose || true

      - name: Fix Slashes in Coverage File
        run: sed -i 's|\\|/|g' coverage/lcov.info || true

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Remove Unwanted Files from Coverage
        run: |
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_empty.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_circle.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_image.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_rect.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_sprite.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_text.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_tile.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_flame/component_flame_tilemap.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_types/component_physics_circle.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_types/component_physics.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/loaded_media_tile.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/tilemap_editor.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/tilemap_editor_page.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/tilemap_editor_page_loaded.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/tilemap_editor_painter.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/tilemap_editor_top_bar.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/tilemap_editor_page.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tilemap/tilemap_editor_page_loaded.dart.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tileset/tileset_editor_page_loaded.dart'  -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/models/component_fields/tileset/tileset_editor_painter.dart'  -o coverage/lcov.info
          
          lcov --remove coverage/lcov.info 'lib/services/api.dart'  -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/main.dart'  -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/theme.dart'  -o coverage/lcov.info
          
          lcov --remove coverage/lcov.info 'lib/pages/play/game_player_object.dart'  -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/pages/play/game_player_ui_object.dart'  -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/pages/play/game_player.dart'  -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/pages/play/play_page.dart'  -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/pages/play/event_manager.dart'  -o coverage/lcov.info

        continue-on-error: true

      - name: Generate Coverage HTML Report
        run: genhtml coverage/lcov.info -o coverage/html || true

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html