name: Push on Epitech repository

on:
  push:


jobs:
  build:
    if: github.repository == 'PlockGames/plock_mobile'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ajoutez une étape pour copier uniquement le dossier 'mobile' dans votre répertoire miroir
      - name: Copy mobile directory
        run: |
          mkdir -p mobile
          cp -r * mobile/
        working-directory: ${{ github.workspace }}
      

      # Configurez Git dans le répertoire miroir
      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # Effectuez l'ajout, le commit et le push des changements dans le répertoire miroir
      - name: Commit files
        run: |
          git add .
          git commit -m "Mirror mobile directory changes"
          git push --force https://github.com/EpitechMscProPromo2025/T-ESP-800-project_esp800-56365-TLS-tiktok_game.git main
