name: Push on Epitech repository

on:
  push:
# ${GITHUB_REPOSITORY#*/}


jobs:
  build:
    if: github.repository == 'PlockGames/plock_mobile'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB }}


      # Configure Git in the root of your Flutter project
      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # Add, commit, and push changes in the root of your Flutter project
      - name: Commit files
        run: |
          cd ${{ github.workspace }}
          git add .
          git commit -m "Mirror mobile directory changes"
          git push --force https://github.com/EpitechMscProPromo2025/T-DEV-800-TLS_2.git $CI_COMMIT_REF_NAME
        env:
          CI_COMMIT_REF_NAME: ${{ github.ref }}
          MY_KEY: ${{ secrets.TOKEN_GITHUB }}
